name: easkripsi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  fl_chart: ^0.65.0
  flutter_bloc: ^8.1.3
  flutter_calendar_carousel: ^2.4.2
  file_picker: ^6.1.1
  flutter_custom_clippers: ^2.1.0
  dashed_path: ^1.0.1
  path_drawing: ^1.0.1
  carousel_slider: ^4.2.1
  table_calendar: ^3.0.9
  intl: ^0.18.1
  emoji_picker_flutter: ^1.6.3
  get: ^4.6.6
  http: ^1.2.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  flutter:
    sdk: flutter
  firebase_auth: ^4.17.8

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  uses-material-design: true
