// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBauwCdVdyYwKgUtGmD9j031jcViyYPkS8',
    appId: '1:1022899410008:web:e3b56f52a74c3bbbcba62d',
    messagingSenderId: '1022899410008',
    projectId: 'easkripsi',
    authDomain: 'easkripsi.firebaseapp.com',
    storageBucket: 'easkripsi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGr_QRnbogKGRSCuwiso98HHVZ13JDiAQ',
    appId: '1:1022899410008:android:ed2a097c5a04f73fcba62d',
    messagingSenderId: '1022899410008',
    projectId: 'easkripsi',
    storageBucket: 'easkripsi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA020AgA4svgQFMsI5gs7_IcnYI2JZSOk8',
    appId: '1:1022899410008:ios:3a4d822485295550cba62d',
    messagingSenderId: '1022899410008',
    projectId: 'easkripsi',
    storageBucket: 'easkripsi.appspot.com',
    iosBundleId: 'com.example.easkripsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA020AgA4svgQFMsI5gs7_IcnYI2JZSOk8',
    appId: '1:1022899410008:ios:f038f69314f58a34cba62d',
    messagingSenderId: '1022899410008',
    projectId: 'easkripsi',
    storageBucket: 'easkripsi.appspot.com',
    iosBundleId: 'com.example.easkripsi.RunnerTests',
  );
}
